---
title: "Results 1d"
#author: "Måns Magnusson"
#date: '2020-07-09'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("../results_experiment1d.rda")
source("experiment_functions.R")
library(ggplot2)
```

## Different kappa

```{r, fig.height=2.5, fig.width=7, echo=FALSE}

# Order
ordr <- order(experiment_jobs$kappa, experiment_jobs$seed)
experiment_jobs <- experiment_jobs[ordr,]
results <- results[ordr]


for(i in 1:length(results)){
  idx <- i
  ggd <- setup_ggplot_data(results[idx], experiment_jobs[idx, c("C_kappa", "kappa")])
  
  plt1 <- ggplot(data = ggd, aes(x = iteration, y = log_post)) + 
    geom_hline(yintercept = -545.5614, lty = "dotted") + 
    geom_hline(yintercept = -648.1314, lty = "dotted") +  
    geom_hline(yintercept = -676.8834, lty = "dotted") +    
    geom_hline(yintercept = -703.6333, lty = "dotted") +    
    geom_line() + #  + ylim(-800, -500) 
    ggtitle(paste0("C_kappa: ", ggd$C_kappa[1], ", kappa: ", ggd$kappa[1]))
  
  
#  plt2 <- ggplot(data = ggd, aes(x = iteration, y = log_post)) + 
#    geom_hline(yintercept = -545.5614, lty = "dotted") + 
#    geom_hline(yintercept = -648.1314, lty = "dotted") +  
#    geom_hline(yintercept = -676.8834, lty = "dotted") +    
#    geom_hline(yintercept = -703.6333, lty = "dotted") +    
#    geom_line() + ylim(-800, -500)

    suppressWarnings(print(plt1))
#  suppressWarnings(print(plt2))
}

```

