# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_count_cpp <- function(state, constants) {
    .Call('PerspectiveTopicModel_init_count_cpp', PACKAGE = 'PerspectiveTopicModel', state, constants)
}

per_sampler_cpp <- function(state, count_matrices, priors, constants) {
    .Call('PerspectiveTopicModel_per_sampler_cpp', PACKAGE = 'PerspectiveTopicModel', state, count_matrices, priors, constants)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('PerspectiveTopicModel_RcppExport_registerCCallable', PACKAGE = 'PerspectiveTopicModel')
})
